package com.yuexin.model;

import java.math.BigDecimal;

public class InvItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.PKID
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.INVNO
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String invno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.CUSTCODE
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String custcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.CUSTNAME
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.ITEMNAME
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String itemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.NUM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.PRICE
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.CASH
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private BigDecimal cash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.TAXITEM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String taxitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.EXATTRIB1
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String exattrib1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.EXATTRIB2
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String exattrib2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.QRY_TXNDATESTA
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String qryTxndatesta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.QRY_TXNDATEEND
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String qryTxndateend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.QRY_IOUNUM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String qryIounum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.QRY_CURRENCYTYPE
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private String qryCurrencytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.QRY_INTAMTSTA
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private BigDecimal qryIntamtsta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ITEM.QRY_INTAMTEND
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    private BigDecimal qryIntamtend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.PKID
     *
     * @return the value of INV_ITEM.PKID
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.PKID
     *
     * @param pkid the value for INV_ITEM.PKID
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.INVNO
     *
     * @return the value of INV_ITEM.INVNO
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getInvno() {
        return invno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.INVNO
     *
     * @param invno the value for INV_ITEM.INVNO
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setInvno(String invno) {
        this.invno = invno == null ? null : invno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.CUSTCODE
     *
     * @return the value of INV_ITEM.CUSTCODE
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getCustcode() {
        return custcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.CUSTCODE
     *
     * @param custcode the value for INV_ITEM.CUSTCODE
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setCustcode(String custcode) {
        this.custcode = custcode == null ? null : custcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.CUSTNAME
     *
     * @return the value of INV_ITEM.CUSTNAME
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.CUSTNAME
     *
     * @param custname the value for INV_ITEM.CUSTNAME
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.ITEMNAME
     *
     * @return the value of INV_ITEM.ITEMNAME
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.ITEMNAME
     *
     * @param itemname the value for INV_ITEM.ITEMNAME
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.NUM
     *
     * @return the value of INV_ITEM.NUM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.NUM
     *
     * @param num the value for INV_ITEM.NUM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.PRICE
     *
     * @return the value of INV_ITEM.PRICE
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.PRICE
     *
     * @param price the value for INV_ITEM.PRICE
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.CASH
     *
     * @return the value of INV_ITEM.CASH
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public BigDecimal getCash() {
        return cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.CASH
     *
     * @param cash the value for INV_ITEM.CASH
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setCash(BigDecimal cash) {
        this.cash = cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.TAXITEM
     *
     * @return the value of INV_ITEM.TAXITEM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getTaxitem() {
        return taxitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.TAXITEM
     *
     * @param taxitem the value for INV_ITEM.TAXITEM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setTaxitem(String taxitem) {
        this.taxitem = taxitem == null ? null : taxitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.EXATTRIB1
     *
     * @return the value of INV_ITEM.EXATTRIB1
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getExattrib1() {
        return exattrib1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.EXATTRIB1
     *
     * @param exattrib1 the value for INV_ITEM.EXATTRIB1
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setExattrib1(String exattrib1) {
        this.exattrib1 = exattrib1 == null ? null : exattrib1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.EXATTRIB2
     *
     * @return the value of INV_ITEM.EXATTRIB2
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getExattrib2() {
        return exattrib2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.EXATTRIB2
     *
     * @param exattrib2 the value for INV_ITEM.EXATTRIB2
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setExattrib2(String exattrib2) {
        this.exattrib2 = exattrib2 == null ? null : exattrib2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.QRY_TXNDATESTA
     *
     * @return the value of INV_ITEM.QRY_TXNDATESTA
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getQryTxndatesta() {
        return qryTxndatesta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.QRY_TXNDATESTA
     *
     * @param qryTxndatesta the value for INV_ITEM.QRY_TXNDATESTA
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setQryTxndatesta(String qryTxndatesta) {
        this.qryTxndatesta = qryTxndatesta == null ? null : qryTxndatesta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.QRY_TXNDATEEND
     *
     * @return the value of INV_ITEM.QRY_TXNDATEEND
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getQryTxndateend() {
        return qryTxndateend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.QRY_TXNDATEEND
     *
     * @param qryTxndateend the value for INV_ITEM.QRY_TXNDATEEND
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setQryTxndateend(String qryTxndateend) {
        this.qryTxndateend = qryTxndateend == null ? null : qryTxndateend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.QRY_IOUNUM
     *
     * @return the value of INV_ITEM.QRY_IOUNUM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getQryIounum() {
        return qryIounum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.QRY_IOUNUM
     *
     * @param qryIounum the value for INV_ITEM.QRY_IOUNUM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setQryIounum(String qryIounum) {
        this.qryIounum = qryIounum == null ? null : qryIounum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.QRY_CURRENCYTYPE
     *
     * @return the value of INV_ITEM.QRY_CURRENCYTYPE
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public String getQryCurrencytype() {
        return qryCurrencytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.QRY_CURRENCYTYPE
     *
     * @param qryCurrencytype the value for INV_ITEM.QRY_CURRENCYTYPE
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setQryCurrencytype(String qryCurrencytype) {
        this.qryCurrencytype = qryCurrencytype == null ? null : qryCurrencytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.QRY_INTAMTSTA
     *
     * @return the value of INV_ITEM.QRY_INTAMTSTA
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public BigDecimal getQryIntamtsta() {
        return qryIntamtsta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.QRY_INTAMTSTA
     *
     * @param qryIntamtsta the value for INV_ITEM.QRY_INTAMTSTA
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setQryIntamtsta(BigDecimal qryIntamtsta) {
        this.qryIntamtsta = qryIntamtsta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ITEM.QRY_INTAMTEND
     *
     * @return the value of INV_ITEM.QRY_INTAMTEND
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public BigDecimal getQryIntamtend() {
        return qryIntamtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ITEM.QRY_INTAMTEND
     *
     * @param qryIntamtend the value for INV_ITEM.QRY_INTAMTEND
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    public void setQryIntamtend(BigDecimal qryIntamtend) {
        this.qryIntamtend = qryIntamtend;
    }
}