package com.yuexin.model;

import java.math.BigDecimal;

public class InvIntdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.PKID
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.CUSTCODE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private String custcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.CUSTNAME
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.CUSTYPE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private String custype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.TXNDATE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private String txndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.INTAMT
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private BigDecimal intamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.TXNTYPE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private String txntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.CURRENCYTYPE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private String currencytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.IOUNUM
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private String iounum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.RECVER
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private String recver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INTDATA.ITEMSTATE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    private String itemstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.PKID
     *
     * @return the value of INV_INTDATA.PKID
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.PKID
     *
     * @param pkid the value for INV_INTDATA.PKID
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.CUSTCODE
     *
     * @return the value of INV_INTDATA.CUSTCODE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public String getCustcode() {
        return custcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.CUSTCODE
     *
     * @param custcode the value for INV_INTDATA.CUSTCODE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setCustcode(String custcode) {
        this.custcode = custcode == null ? null : custcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.CUSTNAME
     *
     * @return the value of INV_INTDATA.CUSTNAME
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.CUSTNAME
     *
     * @param custname the value for INV_INTDATA.CUSTNAME
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.CUSTYPE
     *
     * @return the value of INV_INTDATA.CUSTYPE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public String getCustype() {
        return custype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.CUSTYPE
     *
     * @param custype the value for INV_INTDATA.CUSTYPE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setCustype(String custype) {
        this.custype = custype == null ? null : custype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.TXNDATE
     *
     * @return the value of INV_INTDATA.TXNDATE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public String getTxndate() {
        return txndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.TXNDATE
     *
     * @param txndate the value for INV_INTDATA.TXNDATE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setTxndate(String txndate) {
        this.txndate = txndate == null ? null : txndate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.INTAMT
     *
     * @return the value of INV_INTDATA.INTAMT
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public BigDecimal getIntamt() {
        return intamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.INTAMT
     *
     * @param intamt the value for INV_INTDATA.INTAMT
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setIntamt(BigDecimal intamt) {
        this.intamt = intamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.TXNTYPE
     *
     * @return the value of INV_INTDATA.TXNTYPE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public String getTxntype() {
        return txntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.TXNTYPE
     *
     * @param txntype the value for INV_INTDATA.TXNTYPE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setTxntype(String txntype) {
        this.txntype = txntype == null ? null : txntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.CURRENCYTYPE
     *
     * @return the value of INV_INTDATA.CURRENCYTYPE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public String getCurrencytype() {
        return currencytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.CURRENCYTYPE
     *
     * @param currencytype the value for INV_INTDATA.CURRENCYTYPE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setCurrencytype(String currencytype) {
        this.currencytype = currencytype == null ? null : currencytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.IOUNUM
     *
     * @return the value of INV_INTDATA.IOUNUM
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public String getIounum() {
        return iounum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.IOUNUM
     *
     * @param iounum the value for INV_INTDATA.IOUNUM
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setIounum(String iounum) {
        this.iounum = iounum == null ? null : iounum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.RECVER
     *
     * @return the value of INV_INTDATA.RECVER
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public String getRecver() {
        return recver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.RECVER
     *
     * @param recver the value for INV_INTDATA.RECVER
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setRecver(String recver) {
        this.recver = recver == null ? null : recver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INTDATA.ITEMSTATE
     *
     * @return the value of INV_INTDATA.ITEMSTATE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public String getItemstate() {
        return itemstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INTDATA.ITEMSTATE
     *
     * @param itemstate the value for INV_INTDATA.ITEMSTATE
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    public void setItemstate(String itemstate) {
        this.itemstate = itemstate == null ? null : itemstate.trim();
    }
}