package com.yuexin.model;

public class InvInvinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.PKID
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.INVCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String invcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.INVNO
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String invno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.INVDATE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String invdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.OPTER
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String opter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.MACCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String maccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.TAXCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String taxcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.INVTYPE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String invtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.CUSTCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String custcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.CUSTNAME
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.FADEINVCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String fadeinvcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.FADEINVNO
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String fadeinvno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.BUSKIND
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String buskind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.PAYEE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String payee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.INVVER
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String invver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_INVINFO.REMARK
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.PKID
     *
     * @return the value of INV_INVINFO.PKID
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.PKID
     *
     * @param pkid the value for INV_INVINFO.PKID
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.INVCODE
     *
     * @return the value of INV_INVINFO.INVCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getInvcode() {
        return invcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.INVCODE
     *
     * @param invcode the value for INV_INVINFO.INVCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setInvcode(String invcode) {
        this.invcode = invcode == null ? null : invcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.INVNO
     *
     * @return the value of INV_INVINFO.INVNO
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getInvno() {
        return invno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.INVNO
     *
     * @param invno the value for INV_INVINFO.INVNO
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setInvno(String invno) {
        this.invno = invno == null ? null : invno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.INVDATE
     *
     * @return the value of INV_INVINFO.INVDATE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getInvdate() {
        return invdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.INVDATE
     *
     * @param invdate the value for INV_INVINFO.INVDATE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setInvdate(String invdate) {
        this.invdate = invdate == null ? null : invdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.OPTER
     *
     * @return the value of INV_INVINFO.OPTER
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getOpter() {
        return opter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.OPTER
     *
     * @param opter the value for INV_INVINFO.OPTER
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setOpter(String opter) {
        this.opter = opter == null ? null : opter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.MACCODE
     *
     * @return the value of INV_INVINFO.MACCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getMaccode() {
        return maccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.MACCODE
     *
     * @param maccode the value for INV_INVINFO.MACCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setMaccode(String maccode) {
        this.maccode = maccode == null ? null : maccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.TAXCODE
     *
     * @return the value of INV_INVINFO.TAXCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getTaxcode() {
        return taxcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.TAXCODE
     *
     * @param taxcode the value for INV_INVINFO.TAXCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setTaxcode(String taxcode) {
        this.taxcode = taxcode == null ? null : taxcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.INVTYPE
     *
     * @return the value of INV_INVINFO.INVTYPE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getInvtype() {
        return invtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.INVTYPE
     *
     * @param invtype the value for INV_INVINFO.INVTYPE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setInvtype(String invtype) {
        this.invtype = invtype == null ? null : invtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.CUSTCODE
     *
     * @return the value of INV_INVINFO.CUSTCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getCustcode() {
        return custcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.CUSTCODE
     *
     * @param custcode the value for INV_INVINFO.CUSTCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setCustcode(String custcode) {
        this.custcode = custcode == null ? null : custcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.CUSTNAME
     *
     * @return the value of INV_INVINFO.CUSTNAME
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.CUSTNAME
     *
     * @param custname the value for INV_INVINFO.CUSTNAME
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.FADEINVCODE
     *
     * @return the value of INV_INVINFO.FADEINVCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getFadeinvcode() {
        return fadeinvcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.FADEINVCODE
     *
     * @param fadeinvcode the value for INV_INVINFO.FADEINVCODE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setFadeinvcode(String fadeinvcode) {
        this.fadeinvcode = fadeinvcode == null ? null : fadeinvcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.FADEINVNO
     *
     * @return the value of INV_INVINFO.FADEINVNO
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getFadeinvno() {
        return fadeinvno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.FADEINVNO
     *
     * @param fadeinvno the value for INV_INVINFO.FADEINVNO
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setFadeinvno(String fadeinvno) {
        this.fadeinvno = fadeinvno == null ? null : fadeinvno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.BUSKIND
     *
     * @return the value of INV_INVINFO.BUSKIND
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getBuskind() {
        return buskind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.BUSKIND
     *
     * @param buskind the value for INV_INVINFO.BUSKIND
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setBuskind(String buskind) {
        this.buskind = buskind == null ? null : buskind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.PAYEE
     *
     * @return the value of INV_INVINFO.PAYEE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getPayee() {
        return payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.PAYEE
     *
     * @param payee the value for INV_INVINFO.PAYEE
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setPayee(String payee) {
        this.payee = payee == null ? null : payee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.INVVER
     *
     * @return the value of INV_INVINFO.INVVER
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getInvver() {
        return invver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.INVVER
     *
     * @param invver the value for INV_INVINFO.INVVER
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setInvver(String invver) {
        this.invver = invver == null ? null : invver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_INVINFO.REMARK
     *
     * @return the value of INV_INVINFO.REMARK
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_INVINFO.REMARK
     *
     * @param remark the value for INV_INVINFO.REMARK
     *
     * @mbggenerated Sun Apr 13 16:37:09 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}