package com.yuexin.model;

public class InvLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_LOG.PKID
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_LOG.OPERNAME
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    private String opername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_LOG.OPERTIME
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    private String opertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_LOG.INVNO
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    private String invno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_LOG.OPERINFO
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    private String operinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_LOG.PKID
     *
     * @return the value of INV_LOG.PKID
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_LOG.PKID
     *
     * @param pkid the value for INV_LOG.PKID
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_LOG.OPERNAME
     *
     * @return the value of INV_LOG.OPERNAME
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_LOG.OPERNAME
     *
     * @param opername the value for INV_LOG.OPERNAME
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_LOG.OPERTIME
     *
     * @return the value of INV_LOG.OPERTIME
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    public String getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_LOG.OPERTIME
     *
     * @param opertime the value for INV_LOG.OPERTIME
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    public void setOpertime(String opertime) {
        this.opertime = opertime == null ? null : opertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_LOG.INVNO
     *
     * @return the value of INV_LOG.INVNO
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    public String getInvno() {
        return invno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_LOG.INVNO
     *
     * @param invno the value for INV_LOG.INVNO
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    public void setInvno(String invno) {
        this.invno = invno == null ? null : invno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_LOG.OPERINFO
     *
     * @return the value of INV_LOG.OPERINFO
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    public String getOperinfo() {
        return operinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_LOG.OPERINFO
     *
     * @param operinfo the value for INV_LOG.OPERINFO
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    public void setOperinfo(String operinfo) {
        this.operinfo = operinfo == null ? null : operinfo.trim();
    }
}