package com.yuexin.dao;

import com.yuexin.model.InvIntdata;

public interface InvIntdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_INTDATA
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    int insert(InvIntdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_INTDATA
     *
     * @mbggenerated Sun Apr 13 16:36:27 CST 2014
     */
    int insertSelective(InvIntdata record);
}