package com.yuexin.dao;

import com.yuexin.model.InvItem;

public interface InvItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ITEM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ITEM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    int insert(InvItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ITEM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    int insertSelective(InvItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ITEM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    InvItem selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ITEM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    int updateByPrimaryKeySelective(InvItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ITEM
     *
     * @mbggenerated Sun Apr 13 16:37:36 CST 2014
     */
    int updateByPrimaryKey(InvItem record);
}