package com.yuexin.dao;

import com.yuexin.model.InvLog;

public interface InvLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_LOG
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_LOG
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    int insert(InvLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_LOG
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    int insertSelective(InvLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_LOG
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    InvLog selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_LOG
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    int updateByPrimaryKeySelective(InvLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_LOG
     *
     * @mbggenerated Sun Apr 13 16:37:56 CST 2014
     */
    int updateByPrimaryKey(InvLog record);
}